development:
  sessions:
    default:
      database: hizmetkutusu_backup     
      hosts:
        - localhost:27017
      options:
  options:
    raise_not_found_error: false
 
test:
  sessions:
    default:
      database: hizmetkutusu_test      
      hosts:
        - localhost:27017
      options:
  options:
    raise_not_found_error: false
 
production:
  sessions:
    default:
      uri: mongodb://heroku_app20881436_A:XNieZJwlFcQeHNUhYhCSDwhHyhubIPzU@ds033069.mongolab.com:33069/heroku_app20881436
      
      options:
  options:
    raise_not_found_error: false
 
 
 
